// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKu1eT5Y34fcT_wvbpoOB-BriRylNqQeA',
    appId: '1:299710943417:web:b40a81452592bb0277cb68',
    messagingSenderId: '299710943417',
    projectId: 'milkmate-3946c',
    authDomain: 'milkmate-3946c.firebaseapp.com',
    storageBucket: 'milkmate-3946c.appspot.com',
    measurementId: 'G-0PTJRLMFZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd6qw2rKuqRe2NbpIXS5ITfQE6QE_H_8',
    appId: '1:299710943417:android:a116d6f618e76e9d77cb68',
    messagingSenderId: '299710943417',
    projectId: 'milkmate-3946c',
    storageBucket: 'milkmate-3946c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbPhTX3KHRNezwqcG_b0DnYl0X79IsnqE',
    appId: '1:299710943417:ios:219f919772a8be7677cb68',
    messagingSenderId: '299710943417',
    projectId: 'milkmate-3946c',
    storageBucket: 'milkmate-3946c.appspot.com',
    iosBundleId: 'org.milkmatehub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbPhTX3KHRNezwqcG_b0DnYl0X79IsnqE',
    appId: '1:299710943417:ios:8aafaffed7e55e1a77cb68',
    messagingSenderId: '299710943417',
    projectId: 'milkmate-3946c',
    storageBucket: 'milkmate-3946c.appspot.com',
    iosBundleId: 'com.example.aurora.RunnerTests',
  );
}
